# Generated by Django 4.2.7 on 2023-11-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[{'Nebulosa', 'NEBULOSA'}, {'ESTRELA', 'Estrela'}, {'GALÁXIA', 'Galáxia'}, {'Planeta', 'PLANETA'}], default='', max_length=100),
        ),
    ]
